catalog.name=demo-catalog
catalog.description=Demo service catalog with book search capabilities
catalog.services=books

catalog.routes.books=books/books.camel.yaml
catalog.rules.books=books/books.wanaku-rules.yaml
catalog.dependencies.books=books/books.dependencies.txt
