apiVersion: v1
kind: Service
metadata:
  name: langflow
  labels:
    app: langflow
spec:
  type: ClusterIP
  ports:
  - port: 7860
    targetPort: 7860
    protocol: TCP
    name: http
  selector:
    app: langflow
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: langflow
  labels:
    app: langflow
spec:
  to:
    kind: Service
    name: langflow
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None