apiVersion: v1
kind: Secret
metadata:
  name: langflow-secrets
type: Opaque
data:
  # Base64 encoded values - decode with: echo "value" | base64 -d
  # superuser-password: "changeme" -> Y2hhbmdlbWUK
  superuser-password: cmVkaGF0MTIz
  # secret-key: "K49gl0jZsjp4cEJq_xsIgFwwK_5hFQHhhyNxcQs2NX4" -> SzQ5Z2wwalpzanA0Y0VKcV94c0lnRnd3S181aEZRSGhoeU54Y1FzMk5YNA==
  secret-key: SzQ5Z2wwalpzanA0Y0VKcV94c0lnRnd3S181aEZRSGhoeU54Y1FzMk5YNA==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # password: "langflow" -> bGFuZ2Zsb3c=
  password: bGFuZ2Zsb3c=