name: release

on:
  workflow_dispatch:
    inputs:
      previousDevelopmentVersion:
        description: 'The previous development version (without SNAPSHOT)'
        required: true
      currentDevelopmentVersion:
        description: 'The current development version (without SNAPSHOT)'
        required: true

jobs:
  perform-release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release
        run: |
          find . -iname 'docker-compose.y*ml' -exec sed -i -e "s/wanaku-${{ github.event.inputs.previousDevelopmentVersion }}/wanaku-${{ github.event.inputs.currentDevelopmentVersion }}/g" {} \;
          git add -u 
          git commit -m "Updated docker-compose files for Wanaku release ${{ github.event.inputs.currentDevelopmentVersion }}"
          git tag wanaku-${{ github.event.inputs.currentDevelopmentVersion }}
          git push origin wanaku-${{ github.event.inputs.currentDevelopmentVersion }}
          git push origin main
                    
